# Gas Chromatography with Thermal Conductivity Detection (GC-TCD)

##### **Objective** | Determine the number of components of an unknown mixture and the percent composition of each. {-}


##### **To Turn In** |  *You should turn a ZIP folder containing:* {-}

  1. Your complete lab notebook as an .ipynb file, functioning with no errors.  
  2. Your data files.  
  3. Your completed [analysis sheet](https://github.com/alphonse/alphonse.github.io/raw/master/archive/chem370-s2020/assignments/excel-templates/lab2_gctcd_data-analysis.xlsx).

##### **Student Learning Outcomes** | *By the end of this lab, students will:*    {-}

- Recognize that [gas] chromatography separates a mixture of compounds.  
- Explain how chromatographic peak area relates to composition of a mixture.  
- Estimate the signal to noise ratio (S/N) for a gas chromatograph.
- Relate concepts about polarity from general and organic chemistry to instrumental analysis.  
- Utilize Jupyter as an electronic lab notebook.
- Utilize Octave/MATLAB functions to analyze chromatographic data.  

## Introduction {-}

You will be given mixture of unknown composition for this lab.  It will contain several organic compounds with *similar boiling points*.  You goals are to (1) determine how many components there are in the mixture, (2) determine the percent composition for each compound, and (3) determine the relative polarities of the compounds.

To complete these tasks you will use a gas chromatograph.  Specifically, you will use Gow-Mac 150-series and 400-series isothermal gas chromatographs with thermal conductivity detectors (GC-TCD).  These instruments separate compounds by both boiling point and polarity, and produce a peak for each component wherein the peak area is proportional to the amount of that component present.

Before coming to lab you should be familiar with the concepts presented in the following videos:

- [Chromatography](https://www.youtube.com/watch?v=SnbXQTTHGs4)
- [Gas chromatography](https://www.youtube.com/watch?v=4Xaa9WdXVTM)  
- [Gow-Mac GC-TCDs](https://youtu.be/0fxH9WRKigw) (*optional - we will go over this material in lab*)

## Lab Procedure

### Prepare Samples

1. Obtain a vial containing your unknown mixture from your instructor.  Make sure to record the ID/name in your notebook!  

    > If you don't record the ID you cannot get credit for getting the right answer!

Your runlist for this experiment is:

1. Blank
1. Sample

### Setup the Instrument

*You will need [Vernier Logger Lite](https://www.vernier.com/products/software/logger-lite/#section5) (free) installed on your computer for these steps.*

1. Connect the Instrumentation Amplifier/GoLink! to your computer via USB and open Logger Lite.  
1. Go to **Experiment > Set up sensors > GoLink:1**.  
1. Select **Choose Sensor** and select **Instrumentation Amplifier from the dropdown menu**.  
1. Open the **dropdown menu** again and choose the **0-20 mV** range for the amplifier.
1. Use the **Zero** knob (on the GC) to adjust the signal until the readout is between 1 and 2 mV.

    > Do not touch any other knobs -- they are very sensitive and moving them even a small amount may lead to several additional hours of stabilization time.

1. Let the instrument run for a minute or two until you're cetain the baseline is stable.

    ```{marginfigure}
    The instrument is "stable" when the baseline fluctuates by no more than a few percent of full-scale (20 mV in this case).
    ```

### Load the Syringe

1. Obtain a microliter syringe and clean it with acetone in the syringe cleaning apparatus:   
    1. Place the syringe in the funnel on top of the apparatus.  
    2. Turn on the vacuum pump with the **black on/off switch**.  
    3. Squirt solvent through the syringe.  
    4. Clean the plunger and the needle with a Kimwipe moistened with your solvent.  
1. For a solvent blank:  Pull about 4 $\mu$L acetone into the syringe.  
1. For a samples:
    1. Pull 4 $\mu$L of your sample into the syringe.
    1. Pull air into the syringe until you can clearly see how much sample you loaded.  Record this value in your lab notebook.

### Inject the Sample

1. Make sure the software is running and the instrument is ready to run. (It should be if you completed the steps above and the baseline is stable.)
1. Push the syringe through the septum of the **side B** injection port and then depress the plunger.  Do this step as smoothly and quickly as possible, and be consistent.  

    > The syringe plunger does not go all the way down to the glass body!  Do not force it or you will ruin the syringe!

3. Press the start button in the software.  Again, the key is to be consistent with when you press the start button relative to sample injection!
1. Allow the instrument to run for at least 5 minutes for all peaks to elute.
1. Immediately clean the syringe in the syringe cleaning apparatus, and then repeat the loading and injection steps as needed for all blanks/samples.  Make sure you clean the syringe after the last sample.

### Save the Data

1. When your run is finished, click the **Store** button and then give the run a name in the data viewer on the left side of the screen.
1. When all of your runs have finished go to **File > Export As > CSV** to save your data as a CSV file for processing.

## Data Processing

1. Download the Lab 2 (gowmac) Notebook Template [here](/archive/chem370-s2020/notebooks) and use it for data processing.
1. Place the data files in a directory for this lab.  The recommended path is: `lab-notebooks/lab2_gc-tcd`.
1. Open Jupyter Lab following the steps used before, and then navigate to `lab-notebooks/lab2_gc-tcd` within Jupyter Lab.
1. Create a new Octave notebook inside this directory.  Make sure your data is visible there.
1. Load the CSV files into Octave/Jupyter (see [import data from csv]).  You may also want to plot the data to inspect it.

    ```{octave, eval = FALSE}
    chromatogram = csvread('filename.csv');  # replace 'filename' with your filename
    ```

1. Remove the baseline offset (DC offset) from the data.

    ```{octave, eval = FALSE}
    plot(time, signal);
    xlabel('Time (min)');
    ylabel('Signal (arbitrary)');
    ```

1. Plot the chromatogram with Time on the $x$ axis and signal level on the $y$ axis.

    ```{octave, eval = FALSE}
    ## Define the "baseline" as 4 minutes to end of chromatogram where there are no peaks
    baseline = mean(chromatogram(481:end, 2));

    ## subtract the mean baseline value and store in second column of data set
    chromatogram(:, 2) = chromatogram(:, 2) .- baseline;  
    ```

1. Use the function [`peakArea()`][Find Peak Area] to calculate the area of each peak in your chromatograms.

    ```{octave, eval = FALSE}
    ### You must first run the code shown in the peak area function for this to work!
    ### Copy and paste it into your notebook and run the cell.

    peak1_area = peakArea([chromatogram(:, 1), chromatogram(:, 2)], x1, x2, true);
    ### substitute the lower limit of integration for x1 and the upper limit for x2 (in minutes)
    ### if the last argument is true, a plot will be created

    ### Repeat the function as many times as necessary to integrate each peak.  You will need to change the time for each peak.

    ### ... and so on
    ```

1. Find the percent composition for each peak.  The percent composition for peak $n$ is:

    \[
    C_n(\%)=\frac{A_n}{A_1 + A_2 + ... A_n} \times 100\%
    \]

    where $A_n$ represents the peak area of peak $n$.  Devise a way program this in Octave.

1. Estimate the signal to noise (S/N) ratio for each peak.  S/N is defined as:

    $$
    \frac{S}{N} = \frac{2H}{h} = \frac{\text{Peak Height}}{\text{min-to-max baseline noise}}
    $$

    where $H$ is the peak height at maximum and $h$ is the min-to-max noise in the baseline.  Use the maximum peak height as signal.  The example below shows how to subset the data and find the min and max values.  You will need to calculate $S/N$ from those values according to the formula above.

    ```{octave, eval = FALSE}
    ## find standard deviation of baseline, from 4 minutes to end where there are no peaks
    h = 2 * (max(chromatogram(481:end, 2)) - min(chromatogram(481:end, 2)))

    H1 = max(chromatogram(chromatogram(:, 1) < x, 2)) # x represents dividing line between the two peaks in minutes.
    H2 = max(chromatogram(chromatogram(:, 1) > x, 2)) # x represents dividing line between the two peaks in minutes.
    ```

    <!-- See Section 5.3/Example 5.4 in your textbook for more information. -->

6. Include a discussion of (1) how many constituents are in your sample, (2) the percent composition for each, and (3) the relative polarity of each component.
7. Before turning in your notebook, go to **Kernel > Restart Kernel** and then **Run > Run All**.  Fix any errors before turning in your notebook.
8. Compress your notebook, data file(s), and worksheet into a ZIP folder and upload it to Dropbox (Links for [Monday](https://alphonse.github.io/archive/chem370-s2020/assignments/submissions-monday.html) or [Wednesday](https://alphonse.github.io/archive/chem370-s2020/assignments/submissions-wednesday.html)).
